VALUE_TYPE_RAW = "raw"
VALUE_TYPE_FMT = "fmt"

CATEGORY_DEFAULT_KEY_STATISTICS = "defaultKeyStatistics"
CATEGORY_FINANCIAL_STATISTICS = "financialStatistics"
CATEGORY_SUMMARY_DETAIL = "summaryDetail"

BETA = "beta"
CURRENT_PRICE = "currentPrice"
EBITDA = "ebitda"
EBITDA_MARGINS = "ebitdaMargins"
ENTERPRISE_VALUE = "enterpriseValue"
ENTERPRISE_TO_REVENUE = "enterpriseToRevenue"
ENTERPRISE_TO_EBITDA = "enterpriseToEbitda"
FORWARD_P_TO_E = "forwardPE"
FLOAT_SHARES = "floatShares"
FREE_CASH_FLOW = "freeCashflow"
OPERATING_MARGINS = "operatingMargins"
OPERATING_CASH_FLOW = "operatingCashflow"
PAYOUT_RATIO = "payoutRatio"
TOTAL_REVENUE = "totalRevenue"
SHARES_OUTSTANDING = "sharesOutstanding"
SHARES_SHORT = "sharesShort"
SHORT_SHARES_OF_FLOAT = "shortPercentOfFloat"
SYMBOL = "symbol"
TOTAL_EQUITY_VALUE = "totalEquityValue"
RECOMMENDATION_MEAN = "recommendationMean"
VOLUME = "volume"

CATEGORIES_MULTIPLES_CALCULATION = [
    EBITDA,
    TOTAL_REVENUE,
    FREE_CASH_FLOW,
    OPERATING_CASH_FLOW,
]

CATEGORY_NAME_MAPPER = {
    BETA: "Beta",
    CURRENT_PRICE: "Price",
    EBITDA: "Ebitda",
    EBITDA_MARGINS: "Margin",
    ENTERPRISE_VALUE: "EV",
    ENTERPRISE_TO_REVENUE: "EV/Rev",
    ENTERPRISE_TO_EBITDA: "EV/Ebitda",
    FORWARD_P_TO_E: "forwardPE",
    FLOAT_SHARES: "FloatShares",
    FREE_CASH_FLOW: "FCF",
    OPERATING_CASH_FLOW: "Op.CF",
    OPERATING_MARGINS: "Margin",
    PAYOUT_RATIO: "PO",
    TOTAL_REVENUE: "Revenue",
    SYMBOL: "symbol",
    SHARES_OUTSTANDING: "totalShares",
    SHARES_SHORT: "Sh.Short",
    SHORT_SHARES_OF_FLOAT: "Short.Sh.Float",
    TOTAL_EQUITY_VALUE: "EquityValue",
    RECOMMENDATION_MEAN: "Rec.",
    VOLUME: "vol",
}

FINANCIAL_STATISTICS_CATEGORIES = [
    CURRENT_PRICE,
    EBITDA,
    EBITDA_MARGINS,
    FREE_CASH_FLOW,
    OPERATING_MARGINS,
    OPERATING_CASH_FLOW,
    TOTAL_REVENUE,
    RECOMMENDATION_MEAN,
]

DEFAULT_KEY_STATISTICS_CATEGORIES = [
    ENTERPRISE_VALUE,
    FLOAT_SHARES,
    SHARES_OUTSTANDING,
    SHARES_SHORT,
    SHORT_SHARES_OF_FLOAT,
]

SUMMARY_DETAIL_CATEGORIES = [
    BETA,
    FORWARD_P_TO_E,
    PAYOUT_RATIO,
    VOLUME,
]

